In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[9,8,7],[6,5,4]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]


In [3]:
slicedArr=a[:1,:1]
print(slicedArr)

[[1]]


In [4]:
print(b.sum())

39


In [5]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
mul=np.dot(m1,m2)
print(mul)

[[19 22]
 [43 50]]


In [6]:
mulM = np.multiply(m1,m2)
print(mulM)

[[ 5 12]
 [21 32]]


In [8]:
subM=np.subtract(m2,m1)
print(subM)

[[4 4]
 [4 4]]


In [9]:
m3=np.array([1,2,3,4,5,6,7,8,9])
print(m3)

[1 2 3 4 5 6 7 8 9]


In [11]:
re=m3.reshape(3,3)
print(re)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print("maximumin m3 is",m3.max())
print("min in m3 is",m3.min())
print("max in row 1 is",re.max(axis=1))
print("min in col is",re.min(axis=0))

maximumin m3 is 9
min in m3 is 1
max in row 1 is [3 6 9]
min in col is [1 2 3]


In [13]:
m4=np.array([[4,8,25],[36,48,64]])
print(m4)
print(np.sqrt(m4))
print("stamdard deviation",np.std(m4))

[[ 4  8 25]
 [36 48 64]]
[[2.         2.82842712 5.        ]
 [6.         6.92820323 8.        ]]
stamdard deviation 21.200759944450628


In [14]:
v=np.vstack((m1,m2))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
h=np.hstack((m1,m2))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
vNew=np.vsplit(v,2)
print(vNew)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [17]:
hNew=np.vsplit(h,2)
print(hNew)

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]


In [18]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array


Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [19]:
print("random: {}\n".format(np.random.random(20)));

print("rand: {}\n".format(np.random.rand(3, 4)));

print("randint: {}\n".format(np.random.randint(0, 100, 20)));

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));

random: [0.04739237 0.28029192 0.93397086 0.71623072 0.91234559 0.16251926
 0.55041286 0.71204168 0.51855201 0.31949837 0.32576654 0.21656248
 0.66870263 0.65608452 0.22757687 0.13822326 0.65637952 0.36655271
 0.17508305 0.47433428]

rand: [[0.71475499 0.50212367 0.69244859 0.76407144]
 [0.5991515  0.60942723 0.28236123 0.56616756]
 [0.03671017 0.98969741 0.09570159 0.36917268]]

randint: [73  5 23 71 38  3 49 12 25 69 72  4 21 46 86 78 41 76 11 83]

permutation: [ 4 16  7  3  2 12  1  5  0 15 18  6  8 14  9 13 17 11 10 19]



In [24]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

In [25]:
print("shape a:{}".format(a.shape))
print("ndim {}".format(a.ndim))
print("size {}".format(a.size))
print(f"dtype {a.dtype}")
print(f"itemsize {a.itemsize}")
print(f"data {a.data}")

shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x00000235623A7940>


In [26]:
a1=np.array([[2,3,4,5],
             [1,4,7,6]])
a2=np.array([[1,1,1],[1,1,1]])

In [27]:
#add(), subtract(),mod(),reminder(),multiply(),divide(), power(),absolute()

sliced_arr=a1[:2,:2]
print(sliced_arr)
index_arr=a1[[1,1],[2,1]]
print(index_arr)
print(a1.sum())

[[2 3]
 [1 4]]
[7 4]
32


In [28]:
arr=np.array([[25,64],[89,36]])
print(arr.sum())

214


In [29]:
print(np.sqrt(arr))

[[5.         8.        ]
 [9.43398113 6.        ]]


In [30]:
print(arr.T)

[[25 89]
 [64 36]]


In [31]:
b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[31 36]
 [55 64]]


In [32]:
bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))#any()

all() with axis none False
all() with axis 0 [False  True]


In [33]:
temp=np.arange(9)
print(temp)
re=temp.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
print(np.take(re,[0,1],axis=1))

[[0 1]
 [3 4]
 [6 7]]
